import 'chess_game.dart';

List<ChessGame> chessGames = [
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  ChessGame(date: DateTime.now(), whitePlayerName: 'John', whitePlayerELO: 1560, blackPlayerName: 'Nick', blackPlayerELO: 2102, result: '1-0', moves: 40, timeControl: 'Time Ctrl', timeClass: 'Time Class', wAccuracy: 'W accuracy', bAccuracy: 'B Accuracy', wCPL: 'wCPL', bCPL: 'bCPL'),
  
];